# Generated by Django 2.2.16 on 2023-02-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20230216_1500'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['title', 'slug', 'description'], name='posts_group_title_720f1b_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['slug'], name='slug_idx'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='follow_unique'),
        ),
    ]
