# Generated by Django 2.2.16 on 2023-02-20 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20230220_1824'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='group',
            name='posts_group_title_720f1b_idx',
        ),
    ]
